config/routes.rb
ProjetTutoreMissions::Application.routes.draw do

  get "missions/ordre_mission"

  get "mission/ordre_mission"

  root :to => "home#index"
  ActiveAdmin.routes(self)

  get "users/create"

  devise_for :users

  resources :users do 
    resources :missions do 
      resources :frais_annexes
      resources :frais_repas
      resources :frais_hebergements
      resources :itineraires
      resources :vehicule_persos
      resources :frais_deplacements
      resources :moyen_transports
    end
  end

  get "home/index"

  resources :frais_annexes

  resources :frais_repas

  resources :frais_hebergements

  resources :itineraires

  resources :vehicule_persos

  resources :frais_deplacements

  resources :moyen_transports

  resources :missions

  resources :fichier_pdf

  

  get 'users/new'
  post 'users/create'
  get 'users/:id' => 'user#show'
  get 'users/:id/mission/'

 

  devise_for :users

  devise_scope :user do
    root :to => "users/sessions#new"
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
    get "sign_up", :to => "users/registrations#new"
  end

end

app/models/vehicule_perso.rb
# == Schema Information
#
# Table name: vehicule_persos
#
#  id                                   :integer          not null, primary key
#  numMineralogique                     :string(255)
#  puissanceVehicule                    :integer
#  DateAutorisationAnnuelleDUtilisation :date
#  departement                          :string(255)
#  academie                             :string(255)
#  created_at                           :datetime         not null
#  updated_at                           :datetime         not null
#

class VehiculePerso < ActiveRecord::Base
  attr_accessible :DateAutorisationAnnuelleDUtilisation, :academie, :departement, :numMineralogique, :puissanceVehicule

  validates_presence_of :DateAutorisationAnnuelleDUtilisation, :academie, :departement, :numMineralogique, :puissanceVehicule

end

app/controllers/vehicule_persos_controller.rb
# -*- coding: utf-8 -*-
class VehiculePersosController < ApplicationController
  before_filter :authenticate_user!
  # GET /vehicule_persos
  # GET /vehicule_persos.json
  def index
    @vehicule_persos = VehiculePerso.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @vehicule_persos }
    end
  end

  # GET /vehicule_persos/1
  # GET /vehicule_persos/1.json
  def show
    @vehicule_perso = VehiculePerso.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @vehicule_perso }
    end
  end

  # GET /vehicule_persos/new
  # GET /vehicule_persos/new.json
  def new
    @vehicule_perso = VehiculePerso.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @vehicule_perso }
    end
  end

  # GET /vehicule_persos/1/edit
  def edit
    @vehicule_perso = VehiculePerso.find(params[:id])
  end

  # POST /vehicule_persos
  # POST /vehicule_persos.json
  def create
    @vehicule_perso = VehiculePerso.new(params[:vehicule_perso])

    respond_to do |format|
      if @vehicule_perso.save
        format.html { redirect_to @vehicule_perso, :notice => 'Le véhicule personnel a bien été ajouté' }
        format.json { render :json => @vehicule_perso, :status => :created, :location => @vehicule_perso }
      else
        format.html { render :action => "new" }
        format.json { render :json => @vehicule_perso.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vehicule_persos/1
  # PUT /vehicule_persos/1.json
  def update
    @vehicule_perso = VehiculePerso.find(params[:id])

    respond_to do |format|
      if @vehicule_perso.update_attributes(params[:vehicule_perso])
        format.html { redirect_to @vehicule_perso, :notice => 'Le véhicule personnel a bien été modifié' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @vehicule_perso.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicule_persos/1
  # DELETE /vehicule_persos/1.json
  def destroy
    @vehicule_perso = VehiculePerso.find(params[:id])
    @vehicule_perso.destroy

    respond_to do |format|
      format.html { redirect_to vehicule_persos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vehicule_persos_helper.rb
module VehiculePersosHelper
end

app/views/vehicule_persos/_form.html.erb
<%= simple_form_for(@vehicule_perso) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :numMineralogique ,:label=>"Numero de la plaque mineralogique"%>
    <%= f.input :puissanceVehicule ,:label=>"Puissance du vehicule"%>
    <%= f.input :DateAutorisationAnnuelleDUtilisation ,:label=>"Date de l'autorisation annuelle d'autorisation"%>
    <%= f.input :departement ,:label=>"Departement"%>
    <%= f.input :academie ,:label=>"Academie"%>
  </div>

  <div class="grid-12-12" class="form-actions">
    <%= f.button :submit, :value=>"Valider" %>
  </div>
<% end %>

app/views/vehicule_persos/edit.html.erb
<h1>Gérer les véhicules personnels</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @vehicule_perso %> |
<%= link_to 'Retour', vehicule_persos_path %>

app/views/vehicule_persos/index.html.erb
<h1>Liste des véhicules personnels</h1>

<table>
  <tr>
    <th>Numéro de la plaque minéralogique</th>
    <th>Puissance du véhicule</th>
    <th>Date de l'autorisation annuelle d'autorisation</th>
    <th>Département</th>
    <th>Académie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vehicule_persos.each do |vehicule_perso| %>
  <tr>
    <td><%= vehicule_perso.numMineralogique %></td>
    <td><%= vehicule_perso.puissanceVehicule %></td>
    <td><%= vehicule_perso.DateAutorisationAnnuelleDUtilisation %></td>
    <td><%= vehicule_perso.departement %></td>
    <td><%= vehicule_perso.academie %></td>
    <td><%= link_to 'Afficher', vehicule_perso %></td>
    <td><%= link_to 'Modifier', edit_vehicule_perso_path(vehicule_perso) %></td>
   
    <td><%= link_to 'Supprimer', vehicule_perso, :method => :delete, :data => { :confirm => 'Etes-vous sur?' } %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nouveau véhicule personnel', new_vehicule_perso_path %>

app/views/vehicule_persos/new.html.erb
<h1>Nouveau véhicule personnel</h1>

<%= render 'form' %>

<%= link_to 'Retour', vehicule_persos_path %>

app/views/vehicule_persos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Numéro de la plaque minéralogique:</b>
  <%= @vehicule_perso.numMineralogique %>
</p>

<p>
  <b>Puissance du véhicule:</b>
  <%= @vehicule_perso.puissanceVehicule %>
</p>

<p>
  <b>Date de l'autorisation annuelle d'autorisation:</b>
  <%= @vehicule_perso.DateAutorisationAnnuelleDUtilisation %>
</p>

<p>
  <b>Département:</b>
  <%= @vehicule_perso.departement %>
</p>

<p>
  <b>Académie:</b>
  <%= @vehicule_perso.academie %>
</p>


<%= link_to 'Modifier', edit_vehicule_perso_path(@vehicule_perso) %> |
<%= link_to 'Retour', vehicule_persos_path %>