config/routes.rb
ProjetTutoreMissions::Application.routes.draw do

  get "missions/ordre_mission"

  get "mission/ordre_mission"

  root :to => "home#index"
  ActiveAdmin.routes(self)

  get "users/create"

  devise_for :users

  resources :users do 
    resources :missions do 
      resources :frais_annexes
      resources :frais_repas
      resources :frais_hebergements
      resources :itineraires
      resources :vehicule_persos
      resources :frais_deplacements
      resources :moyen_transports
    end
  end

  get "home/index"

  resources :frais_annexes

  resources :frais_repas

  resources :frais_hebergements

  resources :itineraires

  resources :vehicule_persos

  resources :frais_deplacements

  resources :moyen_transports

  resources :missions

  resources :fichier_pdf

  

  get 'users/new'
  post 'users/create'
  get 'users/:id' => 'user#show'
  get 'users/:id/mission/'

 

  devise_for :users

  devise_scope :user do
    root :to => "users/sessions#new"
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
    get "sign_up", :to => "users/registrations#new"
  end

end

app/models/frais_annex.rb
# == Schema Information
#
# Table name: frais_annexes
#
#  id              :integer          not null, primary key
#  natureDepense   :string(255)
#  depense         :integer
#  nbJustificatifs :integer
#  rembourse       :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class FraisAnnex < ActiveRecord::Base
  attr_accessible :depense, :natureDepense, :nbJustificatifs, :rembourse

  belongs_to :mission

  validates_presence_of :depense, :natureDepense, :nbJustificatifs 
end

app/controllers/frais_annexes_controller.rb
# -*- coding: utf-8 -*-
class FraisAnnexesController < ApplicationController
  before_filter :authenticate_user!


  # GET /frais_annexes
  # GET /frais_annexes.json
  def index
    @frais_annexes = FraisAnnex.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @frais_annexes }
    end
  end

  # GET /frais_annexes/1
  # GET /frais_annexes/1.json
  def show
    @frais_annex = FraisAnnex.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @frais_annex }
    end
  end

  # GET /frais_annexes/new
  # GET /frais_annexes/new.json
  def new
    @frais_annex = FraisAnnex.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @frais_annex }
    end
  end

  # GET /frais_annexes/1/edit
  def edit
    @frais_annex = FraisAnnex.find(params[:id])
  end

  # POST /frais_annexes
  # POST /frais_annexes.json
  def create
    @frais_annex = FraisAnnex.new(params[:frais_annex])

    respond_to do |format|
      if @frais_annex.save
        format.html { redirect_to @frais_annex, :notice => 'Le frais annexe a bien été créé' }
        format.json { render :json => @frais_annex, :status => :created, :location => @frais_annex }
      else
        format.html { render :action => "new" }
        format.json { render :json => @frais_annex.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /frais_annexes/1
  # PUT /frais_annexes/1.json
  def update
    @frais_annex = FraisAnnex.find(params[:id])

    respond_to do |format|
      if @frais_annex.update_attributes(params[:frais_annex])
        format.html { redirect_to @frais_annex, :notice => 'Le frais annexe a bien été modifié' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @frais_annex.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /frais_annexes/1
  # DELETE /frais_annexes/1.json
  def destroy
    @frais_annex = FraisAnnex.find(params[:id])
    @frais_annex.destroy

    respond_to do |format|
      format.html { redirect_to frais_annexes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/frais_annexes_helper.rb
module FraisAnnexesHelper
end

app/views/frais_annexes/_form.html.erb
<%= simple_form_for(@frais_annex) do |f| %>
  <%= f.error_notification %>


  <div class= "form-inputs" >
    <%= f.input :natureDepense ,:label=>"Nature des dépenses" %>
    <%= f.input :depense ,:label=>"Depense" %>
    <%= f.input :nbJustificatifs ,:label=>"Nombre de justificatifs" %>
    <%= f.input :rembourse ,:label=>"Rembourse?" %>
  </div>

  <div class="grid-12-12" class="form-actions">
    <%= f.button :submit, :value=>"Valider" %>
  </div>
<% end %>

app/views/frais_annexes/edit.html.erb
<h1>Gérer les frais annexes</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @frais_annex %> |
<%= link_to 'Retour', frais_annexes_path %>

app/views/frais_annexes/index.html.erb
<h1>Liste des frais annexes</h1>

<table>
  <tr>
    <th>Nature des dépenses</th>
    <th>Depense</th>
    <th>Nombre de justificatifs</th>
    <th>Rembourse?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @frais_annexes.each do |frais_annex| %>
  <tr>
    <td><%= frais_annex.natureDepense %></td>
    <td><%= frais_annex.depense %></td>
    <td><%= frais_annex.nbJustificatifs %></td>
    <td><%= frais_annex.rembourse %></td>
    <td><%= link_to 'Afficher', frais_annex %></td>
   
    <td><%= link_to 'Modifier', edit_frais_annex_path(frais_annex) %></td> 
    <td><%= link_to 'Supprimer', frais_annex, :method => :delete, :data => { :confirm => 'Etes-vous sur?' } %></td>
   
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nouveau frais annexe', new_frais_annex_path %>

app/views/frais_annexes/new.html.erb
<h1>Nouveau frais annexe</h1>

<%= render 'form' %>

<%= link_to 'Retour', frais_annexes_path %>

app/views/frais_annexes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nature des dépenses:</b>
  <%= @frais_annex.natureDepense %>
</p>

<p>
  <b>Depense:</b>
  <%= @frais_annex.depense %>
</p>

<p>
  <b>Nombre de justificatifs:</b>
  <%= @frais_annex.nbJustificatifs %>
</p>

<p>
  <b>Remboursé?:</b>
  <%= @frais_annex.rembourse %>
</p>


<%= link_to 'Modifier', edit_frais_annex_path(@frais_annex) %> |
<%= link_to 'Retour', frais_annexes_path %>