config/routes.rb
ProjetTutoreMissions::Application.routes.draw do

  get "missions/ordre_mission"

  get "mission/ordre_mission"

  root :to => "home#index"
  ActiveAdmin.routes(self)

  get "users/create"

  devise_for :users

  resources :users do 
    resources :missions do 
      resources :frais_annexes
      resources :frais_repas
      resources :frais_hebergements
      resources :itineraires
      resources :vehicule_persos
      resources :frais_deplacements
      resources :moyen_transports
    end
  end

  get "home/index"

  resources :frais_annexes

  resources :frais_repas

  resources :frais_hebergements

  resources :itineraires

  resources :vehicule_persos

  resources :frais_deplacements

  resources :moyen_transports

  resources :missions

  resources :fichier_pdf

  

  get 'users/new'
  post 'users/create'
  get 'users/:id' => 'user#show'
  get 'users/:id/mission/'

 

  devise_for :users

  devise_scope :user do
    root :to => "users/sessions#new"
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
    get "sign_up", :to => "users/registrations#new"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="menuDivPrinc" class="grid-12-12">
<fieldset>
<legend>AppliMission</legend>
<div class="menuDiv">
<fieldset  class="menu">
<legend>Frais</legend>
<p><%= link_to 'Frais annexes', frais_annexes_path %></p>
<p><%= link_to 'Frais déplacement', frais_deplacements_path %></p>
<p><%= link_to 'Frais hébergement', frais_hebergements_path %></p>
<p><%= link_to 'Frais repas', frais_repas_path %></p>
</fieldset>
</div>
<div class="menuDiv">
<fieldset  class="menu">
<legend>Déplacement</legend>
<p><%= link_to 'Itinéraires', itineraires_path %></p>
<p><%= link_to 'Moyens de transport', moyen_transports_path %></p>
<p><%= link_to 'Véhicule personnels', vehicule_persos_path %></p>
</fieldset>
</div>
<div  class="menuDiv">
<fieldset  class="menu">
<legend>Gestion</legend>
<p><%= link_to 'Missions', missions_path %></p>
<p><%= link_to 'Utilisateurs', users_path %></p>
</fieldset>
</div>
<div id="Log">
<% if user_signed_in? %>
  <li>
  <%= link_to('Se déconnecter', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Se connecter', new_user_session_path)  %>  
  </li>
<% end %>
</div>
</fieldset>
</div>