config/routes.rb
ProjetTutoreMissions::Application.routes.draw do

  get "missions/ordre_mission"

  get "mission/ordre_mission"

  root :to => "home#index"
  ActiveAdmin.routes(self)

  get "users/create"

  devise_for :users

  resources :users do 
    resources :missions do 
      resources :frais_annexes
      resources :frais_repas
      resources :frais_hebergements
      resources :itineraires
      resources :vehicule_persos
      resources :frais_deplacements
      resources :moyen_transports
    end
  end

  get "home/index"

  resources :frais_annexes

  resources :frais_repas

  resources :frais_hebergements

  resources :itineraires

  resources :vehicule_persos

  resources :frais_deplacements

  resources :moyen_transports

  resources :missions

  resources :fichier_pdf

  

  get 'users/new'
  post 'users/create'
  get 'users/:id' => 'user#show'
  get 'users/:id/mission/'

 

  devise_for :users

  devise_scope :user do
    root :to => "users/sessions#new"
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
    get "sign_up", :to => "users/registrations#new"
  end

end

app/models/itineraire.rb
# == Schema Information
#
# Table name: itineraires
#
#  id                         :integer          not null, primary key
#  distance                   :integer
#  DateHeureDepartResidence   :date
#  DateArriveeLieuMission     :date
#  DateHeureDepartLieuMission :date
#  DateHeureRetourResidence   :string(255)
#  montant                    :integer
#  rembourse                  :boolean
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#

class Itineraire < ActiveRecord::Base
  attr_accessible :DateArriveeLieuMission, :DateHeureDepartLieuMission, :DateHeureDepartResidence, :DateHeureRetourResidence, :distance, :montant, :rembourse

  belongs_to :mission

  validates_presence_of :DateArriveeLieuMission, :DateHeureDepartLieuMission, :DateHeureDepartResidence, :DateHeureRetourResidence, :distance, :montant

end

app/controllers/itineraires_controller.rb
# -*- coding: utf-8 -*-
class ItinerairesController < ApplicationController
  before_filter :authenticate_user!
  # GET /itineraires
  # GET /itineraires.json
  def index
    @itineraires = Itineraire.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @itineraires }
    end
  end

  # GET /itineraires/1
  # GET /itineraires/1.json
  def show
    @itineraire = Itineraire.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @itineraire }
    end
  end

  # GET /itineraires/new
  # GET /itineraires/new.json
  def new
    @itineraire = Itineraire.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @itineraire }
    end
  end

  # GET /itineraires/1/edit
  def edit
    @itineraire = Itineraire.find(params[:id])
  end

  # POST /itineraires
  # POST /itineraires.json
  def create
    @itineraire = Itineraire.new(params[:itineraire])

    respond_to do |format|
      if @itineraire.save
        format.html { redirect_to @itineraire, :notice => 'L\'itinéraire a bien été créé' }
        format.json { render :json => @itineraire, :status => :created, :location => @itineraire }
      else
        format.html { render :action => "new" }
        format.json { render :json => @itineraire.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /itineraires/1
  # PUT /itineraires/1.json
  def update
    @itineraire = Itineraire.find(params[:id])

    respond_to do |format|
      if @itineraire.update_attributes(params[:itineraire])
        format.html { redirect_to @itineraire, :notice => 'L\'itinéraire a bien été modifié' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @itineraire.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /itineraires/1
  # DELETE /itineraires/1.json
  def destroy
    @itineraire = Itineraire.find(params[:id])
    @itineraire.destroy

    respond_to do |format|
      format.html { redirect_to itineraires_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/itineraires_helper.rb
module ItinerairesHelper
end

app/views/itineraires/_form.html.erb
<%= simple_form_for(@itineraire) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :distance ,:label=>"Distance"%>
    <%= f.input :DateHeureDepartResidence ,:label=>"Date et heure du depart du lieu de residence"%>
    <%= f.input :DateArriveeLieuMission ,:label=>"Date et heure d'arrivee au lieu de la mission"%>
    <%= f.input :DateHeureDepartLieuMission ,:label=>"Date et heure du depart du lieu de la mission"%>
    <%= f.input :DateHeureRetourResidence ,:label=>"Date et heure d'arrivee au lieu de residence"%>
    <%= f.input :montant ,:label=>"Montant"%>
    <%= f.input :rembourse ,:label=>"Rembourse?"%>
  </div>

  <div class="form-actions">
    <%= f.button :submit,:value=>"Valider" %>
  </div>
<% end %>

app/views/itineraires/edit.html.erb
<h1>Gérer les itinéraires</h1>

<%= render 'form' %>

<%= link_to 'Show', @itineraire %> |
<%= link_to 'Back', itineraires_path %>

app/views/itineraires/index.html.erb
<h1>Liste des itinéraires</h1>

<table>
  <tr>
    <th>Distance</th>
    <th>Date et heure du départ du lieu de résidence</th>
    <th>Date et heure d'arrivée au lieu de la mission</th>
    <th>Date et heure du départ du lieu de la mission</th>
    <th>Date et heure d'arrivée au lieu de résidence</th>
    <th>Montant</th>
    <th>Rembourse?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @itineraires.each do |itineraire| %>
  <tr>
    <td><%= itineraire.distance %></td>
    <td><%= itineraire.DateHeureDepartResidence %></td>
    <td><%= itineraire.DateArriveeLieuMission %></td>
    <td><%= itineraire.DateHeureDepartLieuMission %></td>
    <td><%= itineraire.DateHeureRetourResidence %></td>
    <td><%= itineraire.montant %></td>
    <td><%= itineraire.rembourse %></td>
    <td><%= link_to 'Afficher', itineraire %></td>
    <td><%= link_to 'Modifier', edit_itineraire_path(itineraire) %></td>
   
    <td><%= link_to 'Supprimer', itineraire, :method => :delete, :data => { :confirm => 'Etes-vous sur?' } %></td>
   
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nouvel itineraire', new_itineraire_path %>

app/views/itineraires/new.html.erb
<h1>Nouvel itinéraire</h1>

<%= render 'form' %>

<%= link_to 'Retour', itineraires_path %>

app/views/itineraires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Distance:</b>
  <%= @itineraire.distance %>
</p>

<p>
  <b>Date et heure du départ du lieu de résidence:</b>
  <%= @itineraire.DateHeureDepartResidence %>
</p>

<p>
  <b>Date et heure d'arrivée au lieu de la mission:</b>
  <%= @itineraire.DateArriveeLieuMission %>
</p>

<p>
  <b>Date et heure du départ du lieu de la mission:</b>
  <%= @itineraire.DateHeureDepartLieuMission %>
</p>

<p>
  <b>Date et heure d'arrivée au lieu de résidence:</b>
  <%= @itineraire.DateHeureRetourResidence %>
</p>

<p>
  <b>Montant:</b>
  <%= @itineraire.montant %>
</p>

<p>
  <b>Rembourse?:</b>
  <%= @itineraire.rembourse %>
</p>


<%= link_to 'Modifier', edit_itineraire_path(@itineraire) %> |
<%= link_to 'Retour', itineraires_path %>